# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            Radost Stanimirova
tagline:          'Remote sensing, Python, Science'
url:              https://rkstan.github.io/

paginate:         5

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
