remote_theme: fongandrew/hydeout

# Setup
title:            Radost
tagline:          'Remote sensing, Python, Science'
url:              https://rkstan.github.io/

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
