remote_theme: fongandrew/hydeout

# Setup
title:            radost stanimirova
tagline:          'Remote sensing, Python, Science'
url:              https://rkstan.github.io/

# Sidebar link settings
sidebar_home_link:  true
